#!/usr/bin/env bash

VERSION="0.1"

if [ -e $HOME/.vault.config ]; then
    source $HOME/.vault.config;
else
    printf "\e[33mIt looks like the Silent Vault has not been initialized yet.\n"
    printf "Configuration file is missing, please initialize it with -i\e[0m\n"
fi

declare -a options=("SV_MAIN_FOLDER" "SV_GPG_KEY_ID" "SV_BACKUP_FOLDERS")

usage="$(basename "$0") [-h] [-v] [-i] [-o] [-c] [-a]

where:
    -h    show this help text
    -a    about this script
    -v    verify existing configuration
    -i    initialize configuration
    -o    opens Vault (requires PGP key password)
    -c    closes Vault, locks and makes a backup (if backup is configured)"

function about {

cat << EOM

Silent Vault - Encrypted Backup Script (version $VERSION)
https://github.com/nixilla/silent-vault

Small bash script which automates creation and maintainance of the secure local folder,
where you can keep your sensitive information, like cryptocurrency wallets, secret files, etc.

It uses your GPG keys for encryption and signing and can be configured to use Dropbox
and/or other cloud storage provider for backups.

More information can be found at https://github.com/nixilla/silent-vault/blob/master/README.md
EOM
}

function verify {

    DONE=1

    echo "Verifying current configuration ..."

    if type gpg &> /dev/null; then
        printf "gpg available: \e[95m`gpg --version | head -1 | tail -1`\e[0m\n"
    else
        printf "\e[31mgpg not available\e[0m, please install GPG and generate (or import) a key, otherwise this software will not work\n"
        DONE=0
    fi

    if type tar &> /dev/null; then
        printf "tar available: \e[95m`tar --version`\e[0m\n"
    else
        printf "\e[31mtar not available\e[0m, please install tar, otherwise this software will not work\n"
        DONE=0
    fi

    for i in "${options[@]}"
    do
        if [ ${!i} ]; then
	        printf "$i: \e[95m${!i}\e[0m\n"
        else
            DONE=0
            printf "$i: \e[31mhas not been set\e[0m\n"
        fi
    done

    if [ $DONE == 0 ]; then
        printf "\nThe script is not configured, please initialize it with -i \n\n"
        printf "\e[31mverification failed\e[0m\n"
    else
        printf "\e[32mConfiguration OK\e[0m\n"
    fi
}

function init {
    echo "Initializing new configuration ..."

    if [ "$SV_MAIN_FOLDER" == "" ]; then
        SV_MAIN_FOLDER=$HOME/Vault
    fi

    printf "Where would you like to keep your files in decrypted form (default \"\e[95m$SV_MAIN_FOLDER\e[0m\")":

    read SV_MAIN_FOLDER_TMP

    if [ "$SV_MAIN_FOLDER_TMP" != "" ]; then
        SV_MAIN_FOLDER = $SV_MAIN_FOLDER_TMP;
    fi

    gpg --list-keys --keyid-format long
    printf "Please copy and paste one of the following public keys as the answer:\n"
    gpg --list-keys --with-colons | awk -F: '/^pub:/ { print $5 }'
    printf "Which GPG key would you like to use for encryption (\"default: \e[95m$SV_GPG_KEY_ID\e[0m\"): "

    read SV_GPG_KEY_ID_TMP

    if [ "$SV_GPG_KEY_ID_TMP" != "" ]; then
        SV_GPG_KEY_ID = $SV_GPG_KEY_ID_TMP
    fi

    while true; do
        printf "Please folder location where you would like to backup encrypted vault: "
        read FLD

        if [ "$FLD" == "" ]; then
            break;
        fi

        SV_BACKUP_FOLDERS=$SV_BACKUP_FOLDERS,$FLD

    done

    printf "\n\nYour main folder is set to \e[95m$SV_MAIN_FOLDER\e[0m\n"
    printf "Your GPG public key is set to \e[95m$SV_GPG_KEY_ID\e[0m\n"
    printf "Your backup folder are set to \e[95m$SV_BACKUP_FOLDERS\e[0m\n"

    echo -e "Saving ..."
cat << EOM > $HOME/.vault.config
# this file is generated by vault script
export SV_MAIN_FOLDER="$SV_MAIN_FOLDER"
export SV_GPG_KEY_ID="$SV_GPG_KEY_ID"
export SV_BACKUP_FOLDERS="$SV_BACKUP_FOLDERS"
EOM
    echo "OK"
}

function open {
    echo "Opening the Vault ..."

    if [ -e $HOME/.vault.opened ]; then
        printf "\e[33mVault is already opened ... skipping\e[0m\n"
        exit 1
    fi

    if [ -d $SV_MAIN_FOLDER ]; then
        printf "\e[33mYour main folder already exists, please rename/remove it before coninuing ... skipping\e[0m\n"
        exit 1
    fi

    FOLDERS=(${SV_BACKUP_FOLDERS//,/ })

    for i in "${FOLDERS[@]}"; do
        if [ -d $i ]; then
            if [[ -e $i/Vault.tar.gz.gpg && -e $i/Vault.tar.gz.sig ]]; then
                if gpg --verify $i/Vault.tar.gz.sig $i/Vault.tar.gz.gpg; then
                    cp $i/Vault.tar.gz.gpg $HOME/
                    break
                fi
            fi
        fi
    done

    if [ -e $HOME/Vault.tar.gz.gpg ]; then
        if gpg --output $HOME/Vault.tar.gz --decrypt $HOME/Vault.tar.gz.gpg; then
            mkdir $SV_MAIN_FOLDER && tar -xvzf $HOME/Vault.tar.gz -C $SV_MAIN_FOLDER/ &> /dev/null
            rm $HOME/Vault.tar.gz*
            echo date +%s > $HOME/.vault.opened
            printf "\e[32mVault is open\e[0m\n"
        else
            printf "\e[31mVault is not open\e[0m\n"
        fi
    else
        printf "Looks like you creating Vault for the first time\n"
        mkdir $SV_MAIN_FOLDER
        printf "Your Vault has been created in \e[95m$SV_MAIN_FOLDER\e[0m\n"
        echo date +%s > $HOME/.vault.opened
        printf "\e[32mVault is open\e[0m\n"
    fi
}

function close {

    echo "Closing the Vault ..."

    if [ ! -e $HOME/.vault.opened ]; then
        printf "\e[33mVault is not opened ... skipping\e[0m\n"
        exit 1
    fi

    cd $SV_MAIN_FOLDER && tar -zcvf $HOME/Vault.tar.gz . &> /dev/null && cd $OLDPWD
    gpg --encrypt --cipher-algo AES256 --trust-model always --recipient $SV_GPG_KEY_ID $HOME/Vault.tar.gz
    if gpg --output $HOME/Vault.tar.gz.sig --detach-sign $HOME/Vault.tar.gz.gpg &> /dev/null; then

        FOLDERS=(${SV_BACKUP_FOLDERS//,/ })
        for i in "${FOLDERS[@]}"; do
            if [ -d $i ]; then
                echo -n "Copying encrypted Vault files to ${i} ... "
                cp $HOME/Vault.tar.gz.* $i/
                printf "\e[32mOK\e[0m\n"
            fi
        done

        rm -rf $HOME/Vault*
        rm -rf $SV_MAIN_FOLDER
        rm $HOME/.vault.opened

        printf "\e[32mVault is closed\e[0m\n"
    else
        printf "\e[31mVault is not closed\e[0m\n"
    fi


}

while getopts ':chivoa' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    a) about
       exit
       ;;
    v) verify
       exit
       ;;
    i) init
       exit
       ;;
    o) open
       exit
       ;;
    c) close
       exit
       ;;
    \?) printf "Unrecognized option: -%s\n" "$OPTARG,  please use following options:"
       echo "$usage"
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

